services:
  db:
    image: mysql:8.0
    container_name: mysql_glosario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glosario
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_glosario
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

  web:
    image: php:8.2-apache
    container_name: web_glosario
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db